### ISSUE TITLE
Is the contract-hosting system itself open source?

### ISSUE THREAD

**Issue by earonesty** [etleneum/contracts#7]
- if i want a "master list" of contracts, can I always come to this repo?
- is the code for executing and validating the contracts open?
- is there a way of federating the trust for hosting (IE: have N people host, and current state == majority)

**Comment by etleneum** [comment]
1. Yes.
2. Yes: https://github.com/fiatjaf/etleneum
3. Yes, we will certainly do something like that if the site grows a lot.
